### ISSUE TITLE
Segfault when opening show window on linux

### ISSUE THREAD

**Issue by noahsark769** [calband/calchart#10]
The program segfaults whenever I attempt to create a new show or open an existing show. The fault occurs within the `tbarbase.h` wxWidgets library file which is called at line 223 in calchart file `basic_ui.cpp`.

I haven't quite familiarized myself enough yet with the project or wxWidgets to track down the bug, but am working on it. Any guidance would be much appreciated.

**Comment by kmdurand** [comment]
wontfix (if this is really important to you, bring it back)
