### ISSUE TITLE
use wxWidgets 3.0.2

### ISSUE THREAD

**Issue by noahsark769** [calband/calchart#116]
New wxWidgets is out.  Port to that library

**Comment by rmpowell77** [comment]
The release is actually 3.0.2.

There is an issue for building on Mac:
http://trac.wxwidgets.org/ticket/16329

The fix is relatively easy.  But it means those building for Mac have extra steps.

**Comment by noahsark769** [comment]
What's new in the new release? I don't think it's good for people on Mac to
have extra steps, if it's possible to avoid

**Comment by rmpowell77** [comment]
The Mac requires building wxWidgets from scratch anyways, so it's not really a big deal.  The extra step is pretty minor, just curl a patch and apply it:

	$ curl http://trac.wxwidgets.org/raw-attachment/ticket/16329/wx_webview.patch > wx_webview.patch
	$ patch -p0 < wx_webview.patch 

The wxWidgets folks from their postings make it sound like 3.0.2 should be the one to use.  I'm already using it locally and it's not been a problem.  Just need to try out Windows and make sure it's ok.

**Comment by rmpowell77** [comment]
Fixed in #138
