### ISSUE TITLE
Field is Blank

### ISSUE THREAD

**Issue by rmpowell77** [calband/calchart#141]
![capture](https://cloud.githubusercontent.com/assets/6156360/6016193/0f5d1bb8-ab33-11e4-9e46-ba8f1b6cc0af.PNG)

Windows.  Built from TOT with wxwidgets 3.0.2.  tried with 3.0.0 and I get the same thing.

**Comment by rmpowell77** [comment]
@kmdurand Any ideas?

**Comment by rmpowell77** [comment]
Drawing seems completely screwed up on windows for me.  Did I do something wrong?

**Comment by kmdurand** [comment]
Wow, haha, that's a pretty dramatic image right there. I'm still compiling with wxWidgets 3.0.0, but everything's still working fine over here.

**Comment by kmdurand** [comment]
I'll set up wxWidgets 3.0.2 tomorrow and try again with that.

**Comment by kmdurand** [comment]
Everything works for me with wxWidgets 3.0.2; I wonder what's happening on your end...

**Comment by kmdurand** [comment]
Setting the background color seems to be working correctly, at least.

**Comment by kmdurand** [comment]
How does the little preview canvas inside of the preferences window look?

**Comment by rmpowell77** [comment]
preview canvas in preference window looks fine.  Maybe I have some weird out of date issue on my Windows machine.  (I'm not a windows guy...)

**Comment by noahsark769** [comment]
Are you guys using the same visual studio versions? That could be the issue maybe...?

**Comment by kmdurand** [comment]
@rmpowell77 Would you like me to make the Windows 3.4.3 build?

**Comment by rmpowell77** [comment]
@kmdurand Could you?
Check RELEASE_INSTRUCTIONS.txt and start from step 3.  Tag is v3.4.3

**Comment by rmpowell77** [comment]
@kmdurand If you do not have to the SourceForge to post files, I can make you an admin

**Comment by kmdurand** [comment]
@rmpowell77 It would be great to be made an admin, thanks! My username on sourceforge is kmdurand.

**Comment by rmpowell77** [comment]
@kmdurand Ok, you should now be an admin.  Please create the Install Package, upload it to the page.  You'll then need to modify the file settings so that it shows up as the Latest Version (so when users running windows go to the landing page, the new version is linked).  I would then download and install on a different machine (if possible) and make sure everything works.  Then we can close this issue (and announce the new version is available).

**Comment by kmdurand** [comment]
@rmpowell77 The new drum major tried out the new version of CalChart and was able to reproduce the blank field bug, so it looks like we're not quite ready for release after all. We think we figured out the root of the problem, though: his Show Mode preferences were all screwed up. He sent me this picture of his settings:
![problem](https://cloud.githubusercontent.com/assets/3744644/6095855/771cf25e-af26-11e4-9d18-590de3777d11.jpg)

**Comment by kmdurand** [comment]
#152

**Comment by rmpowell77** [comment]
Fixed in #154
