### ISSUE TITLE
Archiving .shw Files

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart#166]
@rmpowell77 has been making efforts to keep our old `.shw` files archived, which is a good idea for a number of reasons. Here are a couple of them:
1. We can use the files to test backwards compatibility
2. We can use the files to help us test new features
3. They're a piece of history, so it's just nice to have them around

The question is, how should we go about storing these? Currently, we have a collection of shows stored in the CalChart repository (in the `\shows` folder). It would be nice to get them out of there, and keep the repository devoted to development of the program only. Ideally, we would put them in a place that is accessible to Stunt. I'm thinking that we could store them through the Amazon web storage that MembersOnly uses. Let me know what you guys think, and if you have any ideas, please put them here!

**Comment by rmpowell77** [comment]
> On Nov 4, 2015, at 3:22 PM, kmdurand <notifications@github.com> wrote:
> 
> @rmpowell77 <https://github.com/rmpowell77> has been making efforts to keep our old .shw files archived, which is a good idea for a number of reasons. Here are a couple of them:
> 
> We can use the files to test backwards compatibility
> We can use the files to help us test new features
> They're a piece of history, so it's just nice to have them around
> The question is, how should we go about storing these? Currently, we have a collection of shows stored in the CalChart repository (in the \shows folder). It would be nice to get them out of there, and keep the repository devoted to development of the program only. Ideally, we would put them in a place that is accessible to Stunt. I'm thinking that we could store them through the Amazon web storage that MembersOnly uses. Let me know what you guys think, and if you have any ideas, please put them here!
> 

Is AWS source controlled?  i.e., can we make sure that the one that is put there was the original file that was used?

**Comment by kmdurand** [comment]
@rmpowell77 I don't believe that AWS is source controlled. It's possible that there's a way for us to set something up to do that, but I haven't looked into it yet. I can see that we might modify the files to bring them up-to-date with the newest CalChart versions; is that the reason why you would recommend source control?

**Comment by rmpowell77** [comment]
I don’t think it’s too bad to keep them in github.  I often keep my test files along with my source files.  They are resources and perhaps ways to show off the tool.

Richard

**Comment by rmpowell77** [comment]
Going to mark this as closed.  We're keeping the files along side with the source code.
