### ISSUE TITLE
Use Spirit for the Continuity Editor Language

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart#171]
We currently use flex/bison for parsing CalChart's Continuity Editor language. We could rewrite the lexer and parser using Spirit to eliminate the need for those tools.

**Comment by kmdurand** [comment]
@rmpowell77 I know that you took a look into this a while back. I'm not sure how far you got, but I had some experience with Spirit while writing the JSON file generator, and was hoping you wouldn't mind me picking up this issue.

**Comment by rmpowell77** [comment]
Great initiative!

I have some code in a branch when I was looking at Spirit and I can revive it.  One issue I was having was with some ambiguous parsing when it came to newlines.  I wasn’t quite sure if Spirit is fully Recursive Decent parsing or if it was PEG based.

I’ll see about pushing up a branch we can play with.

I’ve also been working on developing a way of parsing all the old CalChart shows I have and developing a test suite to make sure our new parsing system is valid.  We should see about getting newer files into the cal chart archives so I have more to test.

Richard

**Comment by rmpowell77** [comment]
Branch at
rmpowell77/spirit_parser

Check it out by building calchart_cmd in the Xcode project on Mac.  Note the HUGE increase in build times (takes about 1 minute to build new_grammar for me)

**Comment by rmpowell77** [comment]
I think we are going to not do this.  The new style for doing Continuity is graphical, having a lexer isn't really needed.  Going to close this one as not to be fixed.
