### ISSUE TITLE
Boost Serialization

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart#172]
@rmpowell77 How would you feel about using the Boost serialization library for saving and loading the CalChartDoc?

**Comment by rmpowell77** [comment]
@kmdurand

Probably would work well!  The core part of CalChart could probably be saved this way, and we could restore the objects easier.

Versioning will be fun!

Richard

**Comment by rmpowell77** [comment]
After some research, this will require linking with boost as boost.serialize isn't header only.  This isn't really a deal breaker.  However, combining that with the fact that we already have a serialization and versioning system I'm not sure we want to switch.  I think we'll probably always want to load older files, so it's going to be hard to just cut over.  And as this is currently working, I'm not sure if we're really going to fix.  I'm going to close this issue out as will not fix.
