### ISSUE TITLE
There should be a select all marchers command

### ISSUE THREAD

**Issue by rmpowell77** [calband/calchart#178]
If there is, I can't find it.

**Comment by brandonchinn178** [comment]
in thr UI, at least, you can open the list of dots and select All, i believe

**Comment by rmpowell77** [comment]
That's right. 

cmd-A (and the equivalent on Windows) should select all.  Brings up the About.  We should be consistent with other apps.

**Comment by rmpowell77** [comment]
Addressed in #194
