### ISSUE TITLE
Remove `calchart_cmd`?

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart#207]
The `calchart_cmd` scheme doesn't build right now, and I don't think we have any intention of fixing it. Could be wrong here; but if that's true, we should probably remove all references from it because it confused a few new users who got a build failure because they didn't know to change the scheme.

**Comment by kmdurand** [comment]
Labeling as a discussion for now; we'll change that depending on the general consensus of what to do about this.

**Comment by rmpowell77** [comment]
Oh, I use it.

I'll fix it so that it builds and that the the appropriate actions are taken for running the All target.

**Comment by rmpowell77** [comment]
Addressed in #219
