### ISSUE TITLE
munkres.h is missing

### ISSUE THREAD

**Issue by rmpowell77** [calband/calchart#228]

**Comment by rmpowell77** [comment]
Kevin, where is this file.

**Comment by kmdurand** [comment]
Ah, forgot to mention that I added a submodule. We could pull in the sources directly if you'd prefer.

**Comment by rmpowell77** [comment]
No worries.  You can just attach here to the thread and I'll patch it up.

**Comment by kmdurand** [comment]
The `.gitmodules` file is included in the pull request that was reverted, so if we restore everything it should work. You'll just need to run `git submodule init` and `git submodule update` before compiling. I edited the `Readme`s here to reflect that: https://github.com/calband/calchart/pull/231

**Comment by rmpowell77** [comment]
fixed in #231
