### ISSUE TITLE
Rotate Tool Snaps To Grid, Causing Strange Effects

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart#252]
Sarah mentioned to me that Stunt is having trouble with the rotate tool in the newest CalChart. I tried it for myself and had the same experience. Right now, all point positions are snapped to the grid for all tools, so if you try to rotate a shape, you won't get a pure rotated version of the original shape.

I've attached screenshots showing a starter formation, a centered CROSSHAIRS position, and the result of a 45 degree rotation around that CROSSHAIRS.

<img width="1312" alt="screen shot 2018-05-23 at 7 06 52 am" src="https://user-images.githubusercontent.com/3744644/40429755-4712ac22-5e58-11e8-9ef7-43761e753a27.png">

<img width="1312" alt="screen shot 2018-05-23 at 7 07 07 am" src="https://user-images.githubusercontent.com/3744644/40429773-5005f58c-5e58-11e8-898e-68e86cb8ec72.png">

<img width="1312" alt="screen shot 2018-05-23 at 7 07 59 am" src="https://user-images.githubusercontent.com/3744644/40429780-55bb54ae-5e58-11e8-89b8-e2bae88560a5.png">

Note that the formation is not a purely rotated version of the original because the marchers are snapped to the grid.

Here is the behavior of 3.4.4, which works as I would expect:

<img width="1392" alt="screen shot 2018-05-23 at 7 19 07 am" src="https://user-images.githubusercontent.com/3744644/40430355-d3178c78-5e59-11e8-9c84-4b1623efebd1.png">

<img width="1392" alt="screen shot 2018-05-23 at 7 19 14 am" src="https://user-images.githubusercontent.com/3744644/40430457-04abd85c-5e5a-11e8-9283-005b47f72cf3.png">

<img width="1392" alt="screen shot 2018-05-23 at 7 19 35 am" src="https://user-images.githubusercontent.com/3744644/40430376-de3cc4ba-5e59-11e8-8a67-d7360ffcd416.png">

**Comment by rmpowell77** [comment]
Ah, this was because of #199 Snap to Grid for points.  What happened was there was feedback that when you did some moves that they wouldn't be on the grid line, which made things difficult for certain moves align between sheets.

This is also fixable by setting the grid spacing to be NONE, and then performing the move.  Perhaps that's a better way to go?  If you want to have Snapping to Grid, set the grid spacing, otherwise, set to none before doing the move?

**Comment by kmdurand** [comment]
Changing the grid spacing to NONE does fix the problem of preserving formation shapes, but it also has the side effect of making it difficult to lock a formation at a sensible angle (e.g. 45 degrees). When the grid size is set to NONE, the rotation angle is affected by every mouse movement, no matter how small. What do you think?

**Comment by rmpowell77** [comment]
Fixed in #270
