### ISSUE TITLE
Sync Windows Visual Studio with Xcode Project Changes

### ISSUE THREAD

**Issue by kmdurand** [calband/calchart#281]
The Windows Visual Studio project for CalChart won't build until it is brought in-sync with all major changes made to the macOS Xcode project. This issue will gather together the pull requests which touch the Xcode project in ways that will ultimately need to be mirrored on Windows before our next build.

We delay these changes because neither Richard or I have easy access to a Windows machine. He uses a virtual machine, and I use a very slow bootable external drive. If any windows developer starts working with us soon, we'd be happy to walk him/her through updating the Windows project so he/she can build.

**Comment by kmdurand** [comment]
We will need to address project changes applied in: https://github.com/calband/calchart/pull/280

**Comment by rmpowell77** [comment]
I think this will get fixed when we merge #284 as we will now use Cmake to keep things consistent.
