### ISSUE TITLE
UI is not opening

### ISSUE THREAD

**Issue by rajrdasani** [calband/calchart#406]
For some reason, after I download calchart and try to open a show file, the file will open, but it will just appear in the taskbar as a white screen, and will not pop open.

For reference, I have been using the new calchart for the last 4-5 weeks or so and everything was working fine then.

**Comment by rmpowell77** [comment]
It may be an issue with that specific show.  Do other shows work?  If you create a new show and save it, does it work?

Would you be able to attach the file?

**Comment by rajrdasani** [comment]
So as an update - it seems that CalChart works fine when I'm at my house, but when I am not at home, no .shw file will open. It will appear in the taskbar as a white square, but will not open.

**Comment by rmpowell77** [comment]
So weird.  Anything new about this?   Perhaps the type of computer of file?

Richard

**Comment by rmpowell77** [comment]
Going to close as resolved because I haven't been able to reproduce.
