### ISSUE TITLE
Anonymous dots on one page, and an algorithm to generate shortest paths to them

### ISSUE THREAD

**Issue by noahsark769** [calband/calchart#78]
This was a suggestion from stunt: what if you had, for example, stuntsheet 1 charted, then could create stuntsheet 2 without assigning any points, and have calchart aotumatically calculate the shortest paths for each one (this is a search problem with on the order of 40,000 possible outcomes, so should be easy to process, and we can start with the algorithm not being very smart).

What do you guys think @kmdurand @rmpowell77?

**Comment by brandonchinn178** [comment]
I posted on Slack, but I found an O(n^4) algorithm for this exact problem! https://en.wikipedia.org/wiki/Hungarian_algorithm

**Comment by rmpowell77** [comment]
I believe this is solved with the Transition Solver feature in CalChart 3.5.
